spring:
  application:
    name: localizacao
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/vendas
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root